export const INCREMENT_COUNT = 'INCREMENT_COUNT';

export const FETCH_ACTIVITIES_STARTED = 'FETCH_ACTIVITIES_STARTED';
export const FETCH_ACTIVITIES_COMPLETED = 'FETCH_ACTIVITIES_COMPLETED';
export const FETCH_ACTIVITIES_FAILED = 'FETCH_ACTIVITIES_FAILED';
